### ISSUE TITLE
Sometimes participants do not appear

### ISSUE THREAD

**Issue by nclaidiere** [open-cogsci/omm-server#116] opened 2022-04-15 07:34 UTC
The list of participants, although filled, does not show up, it only mentions “No participants assigned”. After refreshing (F5) the list often appears again.

**Comment by smathot** [comment] 2022-06-23 19:23
I confirm this.

**Comment by dschreij** [comment] 2022-07-06 06:07
What are the steps you took when this happened? Is it right after you assigned participants to the study? Does it happen most of the time or occasionally? It may be a race condition, in which the participant list is retrieved before they actually have been assigned.

**Comment by nclaidiere** [comment] 2022-07-06 07:37
It happens occasionally, not right after assigning participants, just sometimes. Just refreshing usually solves it.

**Comment by dschreij** [comment] 2022-08-04 13:51
Ah you mean in this area, not the dialog in which you assign participants?

![image](https://user-images.githubusercontent.com/689044/182862331-e1fe6311-1c80-4475-ad3a-ce33da69bf73.png)

This is due to a bug in the component that I used for rendering the list. Likely this occurs at one point after you switch between experiments?

I reported this issue to the maintainer: https://github.com/vuetifyjs/vuetify/issues/12071 but it hasn't been picked up, and I am not sure it ever will :(. We are currently on v2 of that library (Vuetify) and the developers have invested all efforts in v3, so I have noticed that issues for v2 are rarely picked up anymore.

I remember having tried to solve this in the past, but I wasn't able to. Something low-level goes wrong here in the way the library renders this particular component, on which I have little influence from 'outside' of the library, sadly.

**Comment by dschreij** [comment] 2022-08-04 14:08
Nevermind, there was a workaround for that issue, so this must be something else. I have difficult reproducing though. Can one of you give me the _exact_ steps to take before you encounter this problem?

**Comment by dschreij** [comment] 2022-08-04 14:17
Even though I implemented the workaround, the issue I described still appeared to exist for me. I have created a screen recording of what I mean:

https://user-images.githubusercontent.com/689044/182869850-7c75c74f-3731-4d3c-bcbe-f0327b4ba88b.mp4

Can you confirm that we are talking about the same issue, or do you mean something else?

**Comment by dschreij** [comment] 2022-08-04 14:28
I pushed a fix for the issue as described with my screen recording. If you are referring to a different problem, please reopen the issue.

**Closed** 2022-08-04 14:27 UTC
Labels: bug
