### ISSUE TITLE
Allow a greater range of participation priorities and inverse the sorting

### ISSUE THREAD

**Issue by smathot** [open-cogsci/omm-server#94] opened 2021-06-24 09:14 UTC
Right now, priorities have a range between 1 and 99. This should be increased and the mapping should inversed such that low priority values are higher.

**Comment by dschreij** [comment] 2021-07-27 06:55
How high should it be? And the reversal should not be a problem, although there may be some backward compatibility issues for studies that have already assigned priorities to participants, which are suddenly reversed. Since the system is not really used for real studies in production yet, I think this should be ok though.

**Comment by nclaidiere** [comment] 2021-07-28 07:21
Make it 1000 or 999? it's a huge enough number to never reach it. Yes, we're just testing so reversing the order is no problem.

**Comment by dschreij** [comment] 2021-08-10 05:23
Sure that is easy enough to change.

**Comment by dschreij** [comment] 2021-09-01 20:15
@smathot @nclaidiere. For me, the inverse sorting of the priority system feels very counterintuitive. By default, all participants have priority 1, so effectively you can only lower the priority of other participants by giving them a higher value. You cannot easily give a participant a higher priority so it will skip the queue. A solution could be to make the default priority value a participant gets when it is linked to an experiment higher, but it also looks odd if participant by default start with a higher priority value. (and which should this be?). Play around with it yourself and tell me what you think.

**Comment by smathot** [comment] 2021-09-02 08:54
@dschreij I tend to agree. Maybe @nclaidiere can shed some light on this?

**Comment by nclaidiere** [comment] 2021-09-03 07:54
" all participants have priority 1, so effectively you can only lower the priority of other participants by giving them a higher value", yes! that's good. You see priority from the point of view of participants, we see it from the task, participants will be assigned priority 1, 2, 3... for training tasks that they have to complete in order to move on to other tasks. Tasks that are "normal" ongoing research project will be assigned with intermediate priorities and finally background tasks that are done only when there is nothing else going on will have very low priority (i.e. higher numbers). So effectively priority 1 is the highest and that's where any new baboon should start.

Does that make sense?

**Comment by nclaidiere** [comment] 2021-09-03 07:57
Another way to think about it is not in terms of priority but in terms of order of the tasks to be done, number 1 is the first one, then 2, etc.

**Comment by dschreij** [comment] 2021-11-19 20:08
I think that makes it clear. This should work as intended now. Closing the issue.

**Closed by dschreij** 2021-11-19 20:08 UTC
Labels: enhancement
